export const ThreadDB = [
  {
    id:0,
    level: "Beginner",
    date: "Mei 16",
    category: "React",
    title: "Bro, Ada yang pernah menggunakan React Formik ga?? Kalau ada cerita dong.",
    member: "Premium",
    name: "Yaya Naura",
    totalVote: "20",
    totalComments: "120",
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id:1,
    level: "Beginner",
    date: "Jun 8",
    category: "React",
    title: "Apa saja best practices dalam pengembangan aplikasi React?",
    member: "Premium",
    name: "Jennie Blackpink",
    totalVote: "13",
    totalComments: "87",
    image: "https://images.unsplash.com/photo-1569748130764-3fed0c102c59?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id:2,
    level: "Advanced",
    date: "Jul 23",
    category: "React",
    title: "Apa itu Redux dan bagaimana cara mengintegrasikannya dengan React?",
    member: "Premium",
    name: "Lisa Blackpink",
    totalVote: "56",
    totalComments: "83",
    image: "https://images.unsplash.com/photo-1552308995-2baac1ad5490?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id:3,
    level: "intermediet",
    date: "Jan 18",
    category: "React",
    title: "Bagaimana cara mengoptimalkan performa aplikasi React?",
    member: "Premium",
    name: "Roses are rose",
    totalVote: "77",
    totalComments: "90",
    image: "https://images.unsplash.com/photo-1526498460520-4c246339dccb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id:4,
    level: "Advanced",
    date: "Jan 19",
    category: "React",
    title: "Ada yang mau join discord nanti malem? kita belajar bareng yokk",
    member: "Premium",
    name: "Jisoo",
    totalVote: "90",
    totalComments: "111",
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id:5,
    level: "Intermediet",
    date: "Jan 20",
    category: "React",
    title: "Ada yang pernah gunain JEST ga untuk melakukan testing??",
    member: "Premium",
    name: "Wonwoo Seventeen",
    totalVote: "34",
    totalComments: "36",
    image: "https://images.unsplash.com/photo-1569748130764-3fed0c102c59?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
];
